spring:
  config:
    activate:
      on-profile: local-db
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/gc_coffee?serverTimezone=Asia/Seoul
    username: root
    password: 1234